server:
  port: ${APP_PORT}
  undertow:
    threads:
      worker: 10
      io: 2

postgres:
  loquei:
    url: ${DB_HOST}:${DB_PORT}
    schema: ${MAIN_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  security:
    url: ${DB_HOST}:${DB_PORT}
    schema: ${SEC_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

mail:
  port: 587
  username: loquei.project@gmail.com
  password: ${MAIL_PASS}